#!/bin/bash

# Set up environment variables
export PROJECT_ROOT=`git rev-parse --show-toplevel`
export ORBIT_GEN_ROOT=${PROJECT_ROOT}/orbit-gen

# Activate virtual environment
venv_path=${ORBIT_GEN_ROOT}/orbit-gen-venv
/usr/bin/python3.11 -m venv ${venv_path} --upgrade-deps
source ${venv_path}/bin/activate
python3.11 -m pip install -r ${ORBIT_GEN_ROOT}/bin/requirements.txt --cache-dir ${ORBIT_GEN_ROOT}/pip_cache